### ISSUE TITLE
Migration to 14.0

### ISSUE THREAD

**Issue by sergiocorato** [efatto/e-efatto#2]
- [x] connector_whs #19 
- [ ] crm_lead_first_sale
- [ ] crm_lead_product_default
- [x] document_page_usability #11 
- [x] excel_import_export_bom #54 
- [ ] hide_menu_user
- [ ] hr_attendance_work_hour
- [ ] hr_timesheet_productivity
- [x] l10n_it_country_data #3 
- [x] l10n_it_intrastat_tariff #12 
- [x] mail_activity_timeline
- [x] maintenance_plan_step #13 
- [x] mrp_bom_attachment_export #62 
- [ ] mrp_bom_evaluation
- [ ] mrp_bom_evaluation_simple
- [x] mrp_bom_line_group
- [ ] mrp_bom_operation_estimate
- [ ] mrp_bom_sale_pricelist
- [x] mrp_employee_productivity #43 
- [x] mrp_manual_procurement_subcontractor #36 
- [ ] mrp_production_active_move_line_fix
- [ ] mrp_production_bom_change
- [x] mrp_production_bom_create
- [x] mrp_production_calendar #41 
- [x] mrp_production_cancel_confirm #14 
- [ ] mrp_production_change_product_fix
- [x] ~mrp_production_change_qty_fix~ #16 (see comment https://github.com/sergiocorato/e-efatto/pull/16#issuecomment-1735125503)
- [x] mrp_production_child_origin #20 
- [x] mrp_production_component_change #59 
- [x] mrp_production_component_delete #60 
- [x] ~mrp_production_date_planned~ no more needed
- [x] mrp_production_demo #15 
- [ ] mrp_production_deviation #64
- [x] mrp_production_expected_qty #46 
- [x] mrp_production_line_group #56 
- [x] mrp_production_line_mto_manufacture #23 
- [x] mrp_production_lot_custom_assign #57 
- [x] mrp_production_manual_procurement #37 
- [x] mrp_production_preserve_kit_route migrated only to use tests #25 
- [ ] mrp_production_procurement_analytic
- [ ] mrp_production_workorder_fix
- [x] ~mrp_production_workorder_note~ no more needed
- [x] ~mrp_workcenter_capacity~ do not exists anymore
- [x] mrp_workorder_hierarchy #45 
- [x] mrp_workorder_time #44 
- [x] mrp_workorder_timesheet_cost #42 
- [ ] procurement_purchase_analytic_grouping
- [x] product_archiver #53 
- [x] product_attachments_button #58 
- [ ] product_code_no_space
- [ ] product_cost_history
- [ ] product_finishing
- [x] product_managed_replenishment_cost #21 
- [x] product_name_unique #74 
- [ ] product_net_uom
- [x] product_on_hand_translation #5 
- [ ] product_pricelist_bom_cost
- [x] product_pricelist_replenishment_cost #26 
- [ ] product_pricelist_usability
- [x] product_supplierinfo_management #61 
- [x] product_template_listprice_zero_default #4 
- [x] product_template_replenishment_cost #22 
- [ ] product_volume_digits
- [x] purchase_autocomplete_no_invoice #9 
- [x] purchase_autocomplete_no_reference #8 
- [x] purchase_order_approved_vendor #52 
- [x] purchase_order_company_amount #27 
- [ ] purchase_product_weight
- [ ] purchase_product_weight_supplierinfo_update
- [ ] purchase_requisition_grouping
- [ ] purchase_sale_mrp_link
- [ ] purchase_sale_mrp_search
- [ ] purchase_seller_evaluation
- [x] ~purchase_set_stock_move_date~ no more needed
- [x] res_country_logistic_charge #18 
- [x] sale_comment_product #7 
- [x] sale_delivery_recreate #47 
- [ ] sale_line_lot_expiry_alert
- [ ] sale_line_price_history
- [ ] sale_mrp_project_report_qr
- [x] sale_order_activities_kanban #50 
- [ ] sale_order_approved_customer
- [ ] sale_order_archive_project
- [ ] sale_order_contacts
- [ ] sale_order_cost_recalculation
- [x] sale_order_recalculation_visibility #51 
- [ ] sale_report_usability
- [ ] sale_stock_partner_deposit
- [ ] sale_stock_service_procurement_group
- [ ] sale_timesheet_variable_cost
- [ ] stock_barcodes_hr
- [ ] stock_barcodes_mrp
- [x] stock_picking_delivery_report_date #35 
- [ ] stock_picking_note_tree
- [x] stock_picking_note_visibility #24 
- [x] stock_picking_restrict_cancel_with_orig_move_mrp #67 
- [x] stock_picking_transfer_date #66 
- [x] stock_production_lot_info #34
- [x] web_view_usability #6
